INSERT INTO "public"."PRODUCTO" (
    "nombre_producto",
    "val_energia",
    "val_prote",
    "val_grasas_tot",
    "val_grasas_sat",
    "val_monoinsatura",
    "val_poliinsatura",
    "val_grasas_trans",
    "val_colesterol",
    "val_carbono_dis",
    "val_azucar_tot",
    "val_fibra",
    "val_sodio",
    "descripcion",
    "foto_url",
) VALUES (
    'Galletas Rellenas Original 108 g Oreo',
    480,
    4,
    20,
    9,
    8,
    2,
    0,
    0,
    68,
    40,
    null,
    450,
    'Galletas Rellenas',
    'https://static.okto.shop/img/products/s/e9/7e/e97e55370fe4a37b9703f3fe5db80dafc5450ab6_18924.jpg',
);
